upstream api_url {
    server 192.168.1.1:8000;
}
upstream ws_url {
    server 192.168.1.1:9000;
}
server {
    root /usr/share/nginx/html;
    index index.html;
    location /vue-project {
        return 307 http://$http_host/vue-project/;
    }
    location /vue-project/ {
        try_files $uri $uri/ /vue-project/index.html;
    }
    location /api/ {
        proxy_pass http://api_url;
    }
    location /ws/ {
        proxy_pass http://ws_url;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}