/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./src/components/buttons/add-button.vue')['default']
    CancelButton: typeof import('./src/components/buttons/cancel-button.vue')['default']
    ConfirmButton: typeof import('./src/components/buttons/confirm-button.vue')['default']
    CopyButton: typeof import('./src/components/buttons/copy-button.vue')['default']
    CurrentBorder: typeof import('./src/components/current-border.vue')['default']
    DeleteButton: typeof import('./src/components/buttons/delete-button.vue')['default']
    DownloadButton: typeof import('./src/components/buttons/download-button.vue')['default']
    EChart: typeof import('./src/components/e-chart.vue')['default']
    EditButton: typeof import('./src/components/buttons/edit-button.vue')['default']
    LightBorder: typeof import('./src/components/light-border.vue')['default']
    LinkButton: typeof import('./src/components/buttons/link-button.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    QueryButton: typeof import('./src/components/buttons/query-button.vue')['default']
    ResetButton: typeof import('./src/components/buttons/reset-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartButton: typeof import('./src/components/buttons/start-button.vue')['default']
    TablePagination: typeof import('./src/components/table-pagination.vue')['default']
    UploadButton: typeof import('./src/components/buttons/upload-button.vue')['default']
    ViewButton: typeof import('./src/components/buttons/view-button.vue')['default']
  }
}

// For TSX support
declare global {
  const AddButton: typeof import('./src/components/buttons/add-button.vue')['default']
  const CancelButton: typeof import('./src/components/buttons/cancel-button.vue')['default']
  const ConfirmButton: typeof import('./src/components/buttons/confirm-button.vue')['default']
  const CopyButton: typeof import('./src/components/buttons/copy-button.vue')['default']
  const CurrentBorder: typeof import('./src/components/current-border.vue')['default']
  const DeleteButton: typeof import('./src/components/buttons/delete-button.vue')['default']
  const DownloadButton: typeof import('./src/components/buttons/download-button.vue')['default']
  const EChart: typeof import('./src/components/e-chart.vue')['default']
  const EditButton: typeof import('./src/components/buttons/edit-button.vue')['default']
  const LightBorder: typeof import('./src/components/light-border.vue')['default']
  const LinkButton: typeof import('./src/components/buttons/link-button.vue')['default']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const QueryButton: typeof import('./src/components/buttons/query-button.vue')['default']
  const ResetButton: typeof import('./src/components/buttons/reset-button.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const StartButton: typeof import('./src/components/buttons/start-button.vue')['default']
  const TablePagination: typeof import('./src/components/table-pagination.vue')['default']
  const UploadButton: typeof import('./src/components/buttons/upload-button.vue')['default']
  const ViewButton: typeof import('./src/components/buttons/view-button.vue')['default']
}